vars:
  - realdata: RTWIBSE_W22
  - testdata: RTWIBNet_W22
  - MLFLOW_TRACKING_URI: http://172.17.0.4:5000/
stages:
  train:
    cmd: docker run -i --rm --name ludwig_experiment_single --mount type=bind,src=/home/aml/MLOps/data,dst=/app/data
      --mount type=bind,src=/home/aml/MLOps/conf/ludwig_experiment,dst=/app/conf --env MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      ludwig_experiment:3 experiment --config /app/conf/ludwig_conf_sim.yaml --dataset
      /app/data/03_gx_dataprep/03_dataprep_gx_simdata.parquet --output_directory /app/data/04_model_results
      --mlflow --experiment_name relax --model_name simdata
    deps:
    - ./conf/ludwig_experiment/ludwig_conf_sim.yaml
    - ./data/03_gx_dataprep/03_dataprep_gx_simdata.parquet
  data_gen:
    cmd: docker run -i --rm --name data_gen_single --mount type=bind,src=/home/aml/MLOps/data,dst=/app/data --mount type=bind,src=/home/aml/MLOps/src/data_generator,dst=/app/
      data_gen:2
    deps:
    - ./src/data_generator/data_gen.py
    outs:
    - ./data/00_simdata/00_simdata.csv
  data_check:
    cmd: docker run -i --rm --name gx_simdata_single --mount type=bind,src=/home/aml/MLOps/data,dst=/app/data --mount type=bind,src=/home/aml/MLOps/src/gx_datacheck,dst=/app/
      gx_simdata:3
    deps:
    - ./data/00_simdata/00_simdata.csv
    - ./src/gx_datacheck/gx_simdata.py
    outs:
    - ./data/01_gx/01_gx_simdata.csv
  data_prep:
    cmd: docker run -i --rm --name dataprep_simdata_single --mount type=bind,src=/home/aml/MLOps/data,dst=/app/data --mount type=bind,src=/home/aml/MLOps/src/dataprep,dst=/app/ dataprep_simdata:4
    deps:
    - ./data/01_gx/01_gx_simdata.csv
    - ./src/dataprep/dataprep_simdata.py
    outs:
    - ./data/02_dataprep/02_dataprep_simdata.csv
  data_prep_gx:
    cmd: docker run -i --rm --name dataprep_gx_simdata_single --mount type=bind,src=/home/aml/MLOps/data,dst=/app/data --mount type=bind,src=/home/aml/MLOps/src/gx_dataprep,dst=/app/ --env DATAPREP_DATA_FILENAME=/app/data/02_dataprep/02_dataprep_simdata.csv --env DATAPREP_GX_DATA_FILENAME=03_dataprep_gx_simdata.parquet dataprep_gx_data:4
    deps:
    - ./data/02_dataprep/02_dataprep_simdata.csv
    - ./src/gx_dataprep/gx_data_grouped.py
    outs:
    - ./data/03_gx_dataprep/03_dataprep_gx_simdata.parquet
  data_check_real:
    cmd: docker run -i --rm --name gx_realdata_single --mount type=bind,src=/home/aml/MLOps/data,dst=/app/data --mount type=bind,src=/home/aml/MLOps/src/gx_datacheck,dst=/app/ --env REALDATA_LOG_FILENAME=/app/data/00_rawdata/${realdata}/${realdata}_log.csv --env REALDATA_GRADE_FILENAME=/app/data/00_rawdata/${realdata}/${realdata}_grades.csv gx_realdata:3
    deps:
    - ./data/00_rawdata/${realdata}
    - ./src/gx_datacheck/gx_realdata.py
    outs:
    - ./data/01_gx/01_gx_realdata_grades.csv
    - ./data/01_gx/01_gx_realdata_logs.csv
  data_prep_real:
    cmd: docker run -i --rm --name dataprep_realdata_single --mount type=bind,src=/home/aml/MLOps/data,dst=/app/data --mount type=bind,src=/home/aml/MLOps/src/dataprep,dst=/app/ dataprep_realdata:3
    deps:
    - ./data/01_gx/01_gx_realdata_grades.csv
    - ./data/01_gx/01_gx_realdata_logs.csv
    - ./src/dataprep/dataprep_realdata.py
    outs:
    - ./data/02_dataprep/02_dataprep_realdata.csv
  data_prep_gx_real:
    cmd: docker run -i --rm --name dataprep_gx_realdata_single --mount type=bind,src=/home/aml/MLOps/data,dst=/app/data --mount type=bind,src=/home/aml/MLOps/src/gx_dataprep,dst=/app/ dataprep_gx_data:4
    deps:
    - ./data/02_dataprep/02_dataprep_realdata.csv
    - ./src/gx_dataprep/gx_data_grouped.py
    outs:
    - ./data/03_gx_dataprep/03_dataprep_gx_realdata.parquet
  train_real:
    cmd: docker run -i --rm --name ludwig_experiment_single --mount type=bind,src=/home/aml/MLOps/data,dst=/app/data
      --mount type=bind,src=/home/aml/MLOps/conf/ludwig_experiment,dst=/app/conf --env MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      ludwig_experiment:3 experiment --config /app/conf/ludwig_conf_real.yaml --dataset
      /app/data/03_gx_dataprep/03_dataprep_gx_realdata.parquet --output_directory /app/data/04_model_results
      --mlflow --experiment_name relax --model_name realdata
    deps:
    - ./conf/ludwig_experiment/ludwig_conf_real.yaml
    - ./data/03_gx_dataprep/03_dataprep_gx_realdata.parquet
  data_check_test:
    cmd: docker run -i --rm --name gx_testdata_single --mount type=bind,src=/home/aml/MLOps/data,dst=/app/data --mount type=bind,src=/home/aml/MLOps/src/gx_datacheck,dst=/app/ --env REALDATA_LOG_FILENAME=/app/data/00_rawdata/${testdata}/${testdata}_log.csv --env REALDATA_GRADE_FILENAME=/app/data/00_rawdata/${testdata}/${testdata}_grades.csv --env GX_REALDATA_GRADE_FILENAME=01_gx_testdata_grades.csv --env GX_REALDATA_LOG_FILENAME=01_gx_testdata_logs.csv gx_realdata:3
    deps:
    - ./data/00_rawdata/${testdata}
    - ./src/gx_datacheck/gx_realdata.py
    outs:
    - ./data/01_gx/01_gx_testdata_grades.csv
    - ./data/01_gx/01_gx_testdata_logs.csv
  data_prep_test:
    cmd: docker run -i --rm --name dataprep_testdata_single --mount type=bind,src=/home/aml/MLOps/data,dst=/app/data --mount type=bind,src=/home/aml/MLOps/src/dataprep,dst=/app/ --env GX_REALDATA_FILENAME_LOG=./data/01_gx/01_gx_testdata_logs.csv --env GX_REALDATA_FILENAME_GRADES=./data/01_gx/01_gx_testdata_grades.csv --env DATAPREP_REALDATA_FILENAME=02_dataprep_testdata.csv  dataprep_realdata:3
    deps:
    - ./data/01_gx/01_gx_testdata_grades.csv
    - ./data/01_gx/01_gx_testdata_logs.csv
    - ./src/dataprep/dataprep_realdata.py
    outs:
    - ./data/02_dataprep/02_dataprep_testdata.csv
  data_prep_gx_test:
    cmd: docker run -i --rm --name dataprep_gx_testdata_single --mount type=bind,src=/home/aml/MLOps/data,dst=/app/data --mount type=bind,src=/home/aml/MLOps/src/gx_dataprep,dst=/app/ --env DATAPREP_DATA_FILENAME=/app/data/02_dataprep/02_dataprep_testdata.csv --env DATAPREP_GX_DATA_FILENAME=03_dataprep_gx_testdata.parquet dataprep_gx_data:4
    deps:
    - ./data/02_dataprep/02_dataprep_testdata.csv
    - ./src/gx_dataprep/gx_data_grouped.py
    outs:
    - ./data/03_gx_dataprep/03_dataprep_gx_testdata.parquet
  test:
    cmd: python ./src/monitoring_whylogs/monitoring_whylogs_batch.py
    deps:
    - ./data/03_gx_dataprep/03_dataprep_gx_testdata.parquet
    - ./src/monitoring_whylogs/monitoring_whylogs_batch.py
    outs:
    - ./data/05_results/05_results.csv