vars:
  - realdata: RTWIBSE_W22
stages:
  train:
    cmd: docker run -i --rm --name ludwig_experiment_single --mount type=bind,src=/home/aml/MLOps/data,dst=/app/data
      --mount type=bind,src=/home/aml/MLOps/conf/ludwig_experiment,dst=/app/conf --env MLFLOW_TRACKING_URI=http://172.17.0.4:5000/
      ludwig_experiment:2 experiment --config /app/conf/ludwig_conf.yaml --dataset
      /app/data/02_dataprep/02_dataprep_simdata.csv --output_directory /app/data/04_model_results
      --mlflow --experiment_name relax --model_name generator
    deps:
    - ./conf/ludwig_experiment/ludwig_conf.yaml
    - ./data/02_dataprep/02_dataprep_simdata.csv
  data_gen:
    cmd: docker run -i --rm --name data_gen_single --mount type=bind,src=/home/aml/MLOps/data,dst=/app/data --mount type=bind,src=/home/aml/MLOps/src/data_generator,dst=/app/
      data_gen:2
    deps:
    - ./src/data_generator/data_gen.py
    outs:
    - ./data/00_simdata/00_simdata.csv
  data_check:
    cmd: docker run -i --rm --name gx_simdata_single --mount type=bind,src=/home/aml/MLOps/data,dst=/app/data --mount type=bind,src=/home/aml/MLOps/src/gx_datacheck,dst=/app/
      gx_simdata:3
    deps:
    - ./data/00_simdata/00_simdata.csv
    - ./src/gx_datacheck/gx_simdata.py
    outs:
    - ./data/01_gx/01_gx_simdata.csv
  data_prep:
    cmd: docker run -i --rm --name dataprep_simdata_single --mount type=bind,src=/home/aml/MLOps/data,dst=/app/data --mount type=bind,src=/home/aml/MLOps/src/dataprep,dst=/app/ dataprep_simdata:4
    deps:
    - ./data/01_gx/01_gx_simdata.csv
    - ./src/dataprep/dataprep_simdata.py
    outs:
    - ./data/02_dataprep/02_dataprep_simdata.csv
  data_check_real:
    cmd: docker run -i --rm --name gx_realdata_single --mount type=bind,src=/home/aml/MLOps/data,dst=/app/data --mount type=bind,src=/home/aml/MLOps/src/gx_datacheck,dst=/app/ --env REALDATA_LOG_FILENAME=/app/data/00_rawdata/${realdata}/${realdata}_log.csv --env REALDATA_GRADE_FILENAME=/app/data/00_rawdata/${realdata}/${realdata}_grades.csv gx_realdata:3
    deps:
    - ./data/00_rawdata/${realdata}
    - ./src/gx_datacheck/gx_realdata.py
    outs:
    - ./data/01_gx/01_gx_realdata_grades.csv
    - ./data/01_gx/01_gx_realdata_logs.csv
  data_prep_real:
    cmd: docker run -i --rm --name dataprep_realdata_single --mount type=bind,src=/home/aml/MLOps/data,dst=/app/data --mount type=bind,src=/home/aml/MLOps/src/dataprep,dst=/app/ dataprep_realdata:3
    deps:
    - ./data/01_gx/01_gx_realdata_grades.csv
    - ./data/01_gx/01_gx_realdata_logs.csv
    - ./src/dataprep/dataprep_realdata.py
    outs:
    - ./data/02_dataprep/02_dataprep_realdata.csv
  data_prep_gx_real:
    cmd: docker run -i --rm --name dataprep_gx_realdata_single --mount type=bind,src=/home/aml/MLOps/data,dst=/app/data --mount type=bind,src=/home/aml/MLOps/src/gx_dataprep,dst=/app/ dataprep_gx_realdata:3
    deps:
    - ./data/02_dataprep/02_dataprep_realdata.csv
    - ./src/dataprep_gx/gx_realdata_grouped.py
    outs:
    - ./data/01_gx/03_dataprep_gx/03_dataprep_gx_realdata.parquet
  train_real:
    cmd: docker run -i --rm --name ludwig_experiment_single --mount type=bind,src=/home/aml/MLOps/data,dst=/app/data
      --mount type=bind,src=/home/aml/MLOps/conf/ludwig_experiment,dst=/app/conf --env MLFLOW_TRACKING_URI=http://172.17.0.4:5000/
      ludwig_experiment:2 experiment --config /app/conf/ludwig_conf.yaml --dataset
      /app/data/03_dataprep_gx/03_dataprep_gx_realdata.csv --output_directory /app/data/04_model_results
      --mlflow --experiment_name relax_real --model_name real
    deps:
    - ./conf/ludwig_experiment/ludwig_conf.yaml
    - ./data/01_gx/03_dataprep_gx/03_dataprep_gx_realdata.parquet
